var express = require("express");
var path = require("path");
var bodyParser = require("body-parser");
var mongo = require("mongoose");
var sanitize = require("mongo-sanitize");

var db = mongo.connect(
  "mongodb+srv://mercer_mk:Milan.212@products.dotuixf.mongodb.net/Final",
  function (err, response) {
    if (err) {
      console.log(err);
    } else {
      console.log("Connected to database");
    }
  }
);
// Start security code

require("./models/user.model");
require("./models/survey.model");
require("./models/survey_response.model");
require("./controllers/auth.controller");

// Load the REST service for users (generated by express generator)
var usersRouter = require("./routes/users");
var surveyRouter = require("./routes/survey");
var surveyResponseRouter = require("./routes/survey_response");
// End security code

var app = express();
app.use(bodyParser());
app.use(bodyParser.json({ limit: "5mb" }));
app.use(bodyParser.urlencoded({ extended: true }));

var distDir = __dirname + "/dist/Survey-site/";
app.use(express.static(distDir));

app.use(function (req, res, next) {
  res.setHeader("Access-Control-Allow-Origin", "https://comp229-final-project-4gdji8ay6-mercer-mk.vercel.app/");
  res.setHeader(
    "Access-Control-Allow-Methods",
    "GET, POST, OPTIONS, PUT, PATCH, DELETE"
  );
  res.setHeader(
    "Access-Control-Allow-Headers",
    "X-Requested-With,content-type"
  );
  res.setHeader("Access-Control-Allow-Credentials", true);
  next();
});
// Start security code
app.use("/api/users", usersRouter);
app.use("/api/survey", surveyRouter);
app.use("/api/survey_response", surveyResponseRouter);

app.get("*", (request, response) => {
  response.sendFile(path.join(__dirname, "dist/Survey-site/index.html"));
});

var server = app.listen(process.env.PORT || 8000, function () {
  var port = server.address().port;
  console.log("App now running on port", port);
});
